### ISSUE TITLE
Compiling the code

### ISSUE THREAD

**Issue by soerenmueller** [akdess/BAFExtract#1]
Hi guys, 
thanks for sharing your tool, I enjoyed reading your paper on the archive. I'd like to test your BAF approach to identify breakpoints on our single-cell data but run into issues compiling the BAFExtract tool. 

"make: Warning: File `Makefile' has modification time 4.4e+02 s in the future
g++ -c -Wall -O3 main.cpp -o main.o
main.cpp:304:10: error: 't_mapped_PE_read' was not declared in this scope
   vector<t_mapped_PE_read*>* first_mate_reads,
          ^
main.cpp:304:27: error: template argument 1 is invalid
   vector<t_mapped_PE_read*>* first_mate_reads,
                           ^
main.cpp:304:27: error: template argument 2 is invalid
main.cpp:304:10: error: 't_mapped_PE_read' was not declared in this scope
   vector<t_mapped_PE_read*>* first_mate_reads,
          ^
main.cpp:304:27: error: template argument 1 is invalid
   vector<t_mapped_PE_read*>* first_mate_reads,
                           ^
main.cpp:304:27: error: template argument 2 is invalid
main.cpp:304:3: error: 'vector' is not a type
   vector<t_mapped_PE_read*>* first_mate_reads,
   ^
main.cpp:304:9: error: expected ',' or '...' before '<' token
   vector<t_mapped_PE_read*>* first_mate_reads,
         ^
main.cpp: In function 'void dump_nucleotide_pileup_per_SAM_file(char*, std::vector<char*>*, std::vector<int>*, char*, int, int, int&)':
main.cpp:617:144: warning: format '%d' expects a matching 'int' argument [-Wformat=]
         fprintf(stderr, "Loaded pileup is not the same length as the chromosome info: %s: %d, %d\n", chr_ids->at(i_chr), chr_lengths->at(i_chr));
                                                                                                                                                ^
main.cpp: In function 'int main(int, char**)':
main.cpp:976:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i_chr = 0; i_chr < chr_ids->size(); i_chr++)
                             ^
main.cpp:1012:64: warning: array subscript has type 'char' [-Wchar-subscripts]
      bool is_alternate_allele = (nuc_2_num_array[cur_chr_seq[i]] != i_all);
                                                                ^
make: *** [main.o] Error 1"

Hope you have some advice. Thanks!

Soren

**Comment by harmancilab** [comment]
Hi Soren, we failed to correctly update some functions while organizing the code. It should be fixed now. Please let us know if there are more issue.

Thank you for letting us know!
