### ISSUE TITLE
Could not find 1_allele_counts.bin.gz

### ISSUE THREAD

**Issue by SJRussell** [akdess/BAFExtract#3]
Hi there. I am trying to generate BAF files and encountering the error:
`Could not find test/1_allele_counts.bin.gz.`
After using the command: 
`samtools view 14T.bam | ~stewart/BAFExtract/bin/BAFExtract -generate_compressed_pileup_per_SAM stdin ../hg38.list test 50 0; ~stewart/BAFExtract/bin/BAFExtract -get_SNVs_per_pileup ../hg38.list test ../hg38/ 20 4 0.1 14_test.baf`

This is my directory stucture:
[find.txt](https://github.com/akdess/BAFExtract/files/3836222/find.txt)

Thanks in advance

**Comment by akdess** [comment]
Hi, Can you try running the below command by giving the full paths for the files? 

samtools view 14T.bam | ~stewart/BAFExtract/bin/BAFExtract -generate_compressed_pileup_per_SAM stdin ../hg38.list test 50 0;

**Comment by SJRussell** [comment]
For sure. See below:
`$ samtools view 14T.bam | ~stewart/BAFExtract/bin/BAFExtract -generate_compressed_pileup_per_SAM stdin ../CaSpER/hg38.list test 50 0;`
```
Generating pileup from SAM file with min mapp qual 50, min base qual 0
Dumping the pileups per SAM file stdin
Allocating pileup memory.
Done.
Maximum # of alleles at each position: 65536
Phred+33 encoding @ 0. read (6):
AGTTTAACCAAGAAAAGAAGAGAGAAAATCCAAATAACCTCACTAAGAAATGAAACAGGGGATATTACAACTGACACCACTGAAATATTAAAGATTATTCAAGGG
A6EEEEEE6EEE/EEEEEEE/E//A6EEEEEEEEEEEE<EAAE//EE/EEEE/EEAEE/AE6EA/EEE/EE///EEEAEAE<///EAA//EAA/AE<EEE/E/EE
Segmentation fault (core dumped)
```
Any ideas why there is a seg fault?

**Comment by AmandaKedaigle** [comment]
Hi! Has this been solved? I am getting this same seg fault (after giving it *quite* a bit of memory to play with). It doesn't happen with the test bam, so it must be something about my bam file, but I cannot think of what it could be.

**Comment by AmandaKedaigle** [comment]
(one hour later) in my case, I was giving it the wrong chr length .list file (hg38 instead of hg19) - it is running now!

**Comment by ozgunharmanci** [comment]
Hi, thank you for updating with the solution to the issue. We will update the code to make sure that it does not segfault with incorrect reference genome in the arguments.

**Comment by jgarces02** [comment]
Hi, I'm having the same issue. In that case, with the correct reference and requesting a huge amount of RAM...
