### ISSUE TITLE
Cant read baf file

### ISSUE THREAD

**Issue by gonzaparra** [akdess/BAFExtract#4]
Hi,

I am trying to read the baf file that was generated using BAFExtract. 

loh <- readBAFExtractOutput ( path="/dir/CASPER/result", sequencing.type="single-cell")

I get the following error:
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/dir/CASPER/result/NA': No such file or directory

This is the list of files that are present in that folder:
10_allele_counts.bin                  1_allele_counts.bin                   6_mcf_hap5_allele_counts.bin         Un_gl000216_allele_counts.bin  Un_gl000235_allele_counts.bin
11_allele_counts.bin                  1_gl000191_random_allele_counts.bin   6_qbl_hap6_allele_counts.bin         Un_gl000217_allele_counts.bin  Un_gl000236_allele_counts.bin
11_gl000202_random_allele_counts.bin  1_gl000192_random_allele_counts.bin   6_ssto_hap7_allele_counts.bin        Un_gl000218_allele_counts.bin  Un_gl000237_allele_counts.bin
12_allele_counts.bin                  20_allele_counts.bin                  7_allele_counts.bin                  Un_gl000219_allele_counts.bin  Un_gl000238_allele_counts.bin
13_allele_counts.bin                  21_allele_counts.bin                  7_gl000195_random_allele_counts.bin  Un_gl000220_allele_counts.bin  Un_gl000239_allele_counts.bin
14_allele_counts.bin                  21_gl000210_random_allele_counts.bin  8_allele_counts.bin                  Un_gl000221_allele_counts.bin  Un_gl000240_allele_counts.bin
15_allele_counts.bin                  22_allele_counts.bin                  8_gl000196_random_allele_counts.bin  Un_gl000222_allele_counts.bin  Un_gl000241_allele_counts.bin
16_allele_counts.bin                  2_allele_counts.bin                   8_gl000197_random_allele_counts.bin  Un_gl000223_allele_counts.bin  Un_gl000242_allele_counts.bin
17_allele_counts.bin                  3_allele_counts.bin                   9_allele_counts.bin                  Un_gl000224_allele_counts.bin  Un_gl000243_allele_counts.bin
17_ctg5_hap1_allele_counts.bin        4_allele_counts.bin                   9_gl000198_random_allele_counts.bin  Un_gl000225_allele_counts.bin  Un_gl000244_allele_counts.bin
17_gl000203_random_allele_counts.bin  4_ctg9_hap1_allele_counts.bin         9_gl000199_random_allele_counts.bin  Un_gl000226_allele_counts.bin  Un_gl000245_allele_counts.bin
17_gl000204_random_allele_counts.bin  4_gl000193_random_allele_counts.bin   9_gl000200_random_allele_counts.bin  Un_gl000227_allele_counts.bin  Un_gl000246_allele_counts.bin
17_gl000205_random_allele_counts.bin  4_gl000194_random_allele_counts.bin   9_gl000201_random_allele_counts.bin  Un_gl000228_allele_counts.bin  Un_gl000247_allele_counts.bin
17_gl000206_random_allele_counts.bin  5_allele_counts.bin                   M_allele_counts.bin                  Un_gl000229_allele_counts.bin  Un_gl000248_allele_counts.bin
18_allele_counts.bin                  6_allele_counts.bin                   Un_gl000211_allele_counts.bin        Un_gl000230_allele_counts.bin  Un_gl000249_allele_counts.bin
18_gl000207_random_allele_counts.bin  6_apd_hap1_allele_counts.bin          Un_gl000212_allele_counts.bin        Un_gl000231_allele_counts.bin  X_allele_counts.bin
19_allele_counts.bin                  6_cox_hap2_allele_counts.bin          Un_gl000213_allele_counts.bin        Un_gl000232_allele_counts.bin  Y_allele_counts.bin
19_gl000208_random_allele_counts.bin  6_dbb_hap3_allele_counts.bin          Un_gl000214_allele_counts.bin        Un_gl000233_allele_counts.bin  result.baf
19_gl000209_random_allele_counts.bin  6_mann_hap4_allele_counts.bin         Un_gl000215_allele_counts.bin        Un_gl000234_allele_counts.bin

Thanks in advance

**Comment by gonzaparra** [comment]
I guess the problem is related to my folder not containing files with "snp" suffix, which is the value by default for that function. I changed it to baf, is that correct to do?

Should I have snp files in that folder?

Thanks

Gonzalo

**Comment by akdess** [comment]
Dear Gonzalo, 
Thanks a lot for your interest!
You should change the suffix to “.baf”. Sorry for the confusion. I will update the tutorials.
