### ISSUE TITLE
Can BAFExtract Extract BAF values from Genomic Sequencing Bam files?

### ISSUE THREAD

**Issue by xysj1989** [akdess/BAFExtract#7]
Hi!

I have several bam files generated from Whole Genomes Sequencing and Whole Exome Sequencing. Is it possible to use BAFExtract to extract BAF values from these DNA-Seq bam files? Or BAFExtract is for BAF values Extraction only from RNA-Seq bam files?

Best.

**Comment by akdess** [comment]
Hi @xysj1989 , I am very sorry for my late reply. 
Sure you can also run it on DNA-Seq bam files.
